---
# author: lework

- name: Ensure docker history packages are removed.
  yum: "name={{ item }} state=removed"
  with_items: "{{ docker_old }}"

- name: Install yum-utils
  yum: name=yum-utils
   
- name: Install docker repo.
  shell: "yum-config-manager --add-repo {{ docker_repo }}"
 
- name: Ensure docker packages are installed.
  yum: "name={{ item }} state=installed  update_cache=yes"
  with_items: "{{ docker_packages }}"
  
- name: Modify the docker software source for keda.
  replace:
    path: /etc/yum.repos.d/docker-ce.repo
    regexp: 'download\.docker\.com'
    replace: "mirrors.ustc.edu.cn/docker-ce"

- name: Create Docker config directory.
  file: path=/etc/docker state=directory

- name: Configure docker startup parameters.
  template:
    src: daemon.json.j2
    dest: "/etc/docker/daemon.json"

- name: clear yum
  shell: yum-complete-transaction --cleanup-only

- name: Ensure docker-ce packages are installed.
  yum: "name={{ item }} state=present "
  with_items: "{{ docker_ce_packages }}"

- name: Ensure docker is started and enabled at boot.
  systemd: name=docker state=started enabled=yes
  when: docker_start
