- hosts: k8s-cluster
  vars:
   - ipnames:
      '182.10.1.78': 'master'
      '182.10.1.79': 'node79'
      '182.10.1.83': 'node83'
      '182.10.1.84': 'node84'
  roles:
    - hostnames

- hosts: 182.10.1.79
  serial: "100%"
  any_errors_fatal: true
  roles:
    - repo-epel
    - docker

- hosts: 182.10.1.79
  vars:
    kubernetes_role: node
    kubernetes_version: '1.13'
    kubernetes_version_rhel_package: '1.13.1'    #  '1.12.1~7'   '1.13.1~5'   '1.14.0'
  roles:
    - geerlingguy.kubernetes
