- name: create k8s.txt
  shell: "curl https://raw.githubusercontent.com/woshijiqinga/ansible/master/geerlingguy.kubernetes/templates/sh/addon.sh  | bash "

- name: start k8s-proxy
  shell: "curl https://raw.githubusercontent.com/woshijiqinga/ansible/master/geerlingguy.kubernetes/templates/sh/k8s-proxy.sh -o /root/k8s-proxy.sh"

- name: start kubelet proxy
  shell: "bash /root/k8s-proxy.sh {{ api_port }}  && rm -rf /root/k8s-proxy.sh"

- name: bash alias.sh
  shell: "curl https://raw.githubusercontent.com/woshijiqinga/ansible/master/geerlingguy.kubernetes/templates/sh/alias.sh | bash"

- name: source /root/.bashrc
  shell: "curl https://raw.githubusercontent.com/woshijiqinga/ansible/master/geerlingguy.kubernetes/templates/sh/source.sh | bash "
