- name: Enable the Kubernetes Web Dashboard UI (if configured).
  command: "kubectl create -f {{ kubernetes_web_ui_manifest_file }}"

- name: create dashboard_adminuser
  shell: "kubectl apply -f {{ kubernetes_dashboard_adminuser }}"

#- name: create metrics-server
#  shell: "kubectl  apply -f /etc/ansible/roles/geerlingguy.kubernetes/templates/metrics-server/1.8+/"

- name: create heapster+influxdb+grafana
  shell: "kubectl apply -f https://raw.githubusercontent.com/woshijiqinga/ansible/master/geerlingguy.kubernetes/templates/heapster/heapster.yaml  && kubectl apply -f https://raw.githubusercontent.com/woshijiqinga/ansible/master/geerlingguy.kubernetes/templates/heapster/influxdb.yaml && kubectl apply -f https://raw.githubusercontent.com/woshijiqinga/ansible/master/geerlingguy.kubernetes/templates/heapster/grafana.yaml"

- name: create efk
  shell: "kubectl apply -f https://raw.githubusercontent.com/woshijiqinga/ansible/master/geerlingguy.kubernetes/templates/efk/filebeat.yaml && kubectl apply -f https://raw.githubusercontent.com/woshijiqinga/ansible/master/geerlingguy.kubernetes/templates/efk/elasticsearch.yml && kubectl apply -f https://raw.githubusercontent.com/woshijiqinga/ansible/master/geerlingguy.kubernetes/templates/efk/kibana.yml"

- name: install wget
  yum: name=wget

- name: install jq
  yum: name=jq

- name: install helm
  shell: find /etc/ansible -name helm-v2.13.1-linux-amd64.tar.gz -exec tar xf {} -C /root \; && mv /root/linux-amd64/helm /usr/local/bin/  && rm -rf  /root/linux-amd64
#  ignore_errors: true

- name: helm init
  shell: "helm init && helm init --client-only --stable-repo-url https://aliacs-app-catalog.oss-cn-hangzhou.aliyuncs.com/chart "

- name: add helm repo
  shell: helm repo add incubator https://aliacs-app-catalog.oss-cn-hangzhou.aliyuncs.com/charts-incubator/ 

- name: install tiller
  shell: "helm init --service-account tiller --upgrade -i registry.cn-hangzhou.aliyuncs.com/google_containers/tiller:v2.13.1  --stable-repo-url https://kubernetes.oss-cn-hangzhou.aliyuncs.com/charts &&  helm init --service-account tiller --upgrade -i registry.cn-hangzhou.aliyuncs.com/google_containers/tiller:v2.13.1 --tiller-tls-cert /etc/kubernetes/ssl/tiller001.pem --tiller-tls-key /etc/kubernetes/ssl/tiller001-key.pem --tls-ca-cert /etc/kubernetes/ssl/ca.pem --tiller-namespace kube-system --stable-repo-url https://kubernetes.oss-cn-hangzhou.aliyuncs.com/charts "
#  ignore_errors: true

- name: create tiller user
  shell: kubectl create serviceaccount --namespace kube-system tiller &&  kubectl create clusterrolebinding tiller-cluster-rule --clusterrole=cluster-admin --serviceaccount=kube-system:tiller && kubectl patch deploy --namespace kube-system tiller-deploy -p '{"spec":{"template":{"spec":{"serviceAccount":"tiller"}}}}'
#  ignore_errors: true

- name: create completion helm
  shell: echo "source <(helm completion bash)" >> /root/.bashrc

