---
- name: bootstrap | Turn off the swap.
  shell: swapoff -a && sed -ri '/^[^#]*swap/s@^@#@' /etc/fstab

- name: Ensure Kubernetes repository exists.
  yum_repository:
    name: kubernetes
    description: Kubernetes
    enabled: true
    gpgcheck: true
    repo_gpgcheck: true
    baseurl: https://mirrors.aliyun.com/kubernetes/yum/repos/kubernetes-el7-x86_64/
    gpgkey:
      - https://mirrors.aliyun.com/kubernetes/yum/doc/yum-key.gpg 
      - https://mirrors.aliyun.com/kubernetes/yum/doc/rpm-package-key.gpg

- name: Add Kubernetes GPG keys.
  rpm_key:
    key: "{{ item }}"
    state: present
  register: kubernetes_rpm_key
  with_items:
      - https://mirrors.aliyun.com/kubernetes/yum/doc/yum-key.gpg 
      - https://mirrors.aliyun.com/kubernetes/yum/doc/rpm-package-key.gpg

- name: Make cache if Kubernetes GPG key changed.
  command: "yum -q makecache -y --disablerepo='*' --enablerepo='kubernetes'"
  when: kubernetes_rpm_key is changed
  args:
    warn: false
